### PR TITLE
Correction Pull Request (?)

### PR DESCRIPTION
**Pull request by ghost**
some things. see the commit description (?) :)
##markdown
And Yess.... Thank you for this Page ^^ everything worked well and i could try anything.
Except the Cron Jobs and some IDE's, because they needed a GUI i think. But it was interesting and good written :D

### CODE REVIEW

**Comment by ghost** [comment]
COOOOOMMMMMEEEENTTT

**Comment by ghost** [comment]
Danke🎅😅🎄

**Comment by AnonymerNiklasistanonym** [comment]
I'm glad you liked the content and that it helped you :smiley:
I probably add a Cron job tutorial for non gui systems on Linux because that is totally possible and not that difficult! Thanks for this idea, totally forgot it :relieved:
Also thanks for your corrections and additions to this repository :heart:

**Comment by AnonymerNiklasistanonym** [comment]
Added a `cron` job tutorial for the terminal (d28a4e6fb68bc16c26d1a531155bddac18eae8da) - thank you again for reminding me to do this 😄

**Pull request merged**
